### PR TITLE
[next] Fix `config set` not respecting property types

### LINKED ISSUE #772: zowe config set "profiles.profilename.properties.propertyname" "12345" always defines numeric value regardless of what is defined in the zowe.schema.json

### PR DESCRIPTION
**Pull request by t1m0thyj**
Resolves #772

I've attempted to make the new method `ConfigSchema.findPropertyType` flexible and easy to use not only in the CLI, but also in apps that use the ProfileInfo API like Zowe Explorer.

### CODE REVIEW

File: packages/config/src/ConfigSchema.ts [hunk 1]
```diff
@@ -420,4 +422,34 @@ export class ConfigSchema {
...
+
+        const profileSchemas = schema ? this.loadSchema(schema) : ImperativeConfig.instance.loadedConfig.profiles;
+        const profileSchema = profileSchemas.find(p => p.type === profileType)?.schema;
+        if (profileSchema?.properties[propertyName] == null) {
+            return;
+        }
+
+        // TODO How to handle profile property with multiple types
+        const propertyType = profileSchema.properties[propertyName].type;
+        return Array.isArray(propertyType) ? propertyType[0] : propertyType;
```
Comment (zFernand0) [inline packages/config/src/ConfigSchema.ts:453]: good question 😋

**Review by zFernand0 — APPROVED** [review]
LGTM

**Review by awharn — APPROVED** [review]
