### PR TITLE
Fix `--response-format-json` issues in daemon mode

### LINKED ISSUE #842: `zowe --version --rfj` returns an extra `\n` in the version field
```
$ zowe --version --rfj

{
  "success": true,
  "exitCode": 0,
  "message": "Version displayed",
  "stdout": "6.37.2\n",
  "stderr": "",
  "data": {
    "version": "6.37.2\n"
  }
}
```

The `version` field is not just version but it has an extra `\n` like in `6.37.2\n` in the example. It causes problems in automation that tries to ensure expected version but the workaround is easy.

### PR DESCRIPTION
**Pull request by t1m0thyj**
Fixes #842 and #843

### CODE REVIEW

**Review by awharn — APPROVED** [review]

File: packages/cmd/src/yargs/YargsConfigurer.ts [hunk 1]
```diff
@@ -48,17 +48,8 @@ export class YargsConfigurer {
         /**
          * Add the command definitions to yargs
          */
-        const jsonResponseFormat =
```
Comment (gejohnston) [inline packages/cmd/src/yargs/YargsConfigurer.ts:51]: What was it about this code that was failing, causing you to use a different implementation in getResponseFormat( )?

**Review by gejohnston — APPROVED** [review]
I am sure that you made it work. I just had a question for my own understanding.

File: packages/cmd/src/yargs/YargsConfigurer.ts (hunk 1 above)
Comment (t1m0thyj) [reply packages/cmd/src/yargs/YargsConfigurer.ts:51]: Previously we were checking `process.argv` when Imperative initialized to look for the `--response-format-json` argument. This worked in Zowe v1, but no longer works in Zowe v2 with daemon mode because:
* `process.argv` contains the arguments that the daemon server was launched with (`--daemon`), not the arguments passed to the current command.
* The CLI arguments need to be reloaded every time the daemon client issues a command, rather than being cached at the time Imperative initializes.

**Review by zFernand0 — APPROVED** [review]
