### PR TITLE
Fix #54 where 0 could not be specified for positionals (lts-incremental)

### LINKED ISSUE #54: Specifying 0 for a positional numeric parameter results in "missing operand"
_From @tucker01 on April 26, 2018 18:2_

Example:
```
bright jobs view spool-file-by-id J123 0
Syntax Error:
Missing positional parameters: spoolfileid.
The spool file ID number for the spool file to view. Use the "imperative
zos-jobs list spool-files-by-jobid" command to obtain spool ID numbers.No
pre-validation of the ID is performed.
Use "bright jobs view spool-file-by-id --help" to view command description,
usage, and options.
```

Checkout `SyntaxValidator.validateSyntax()` for the culprit.

_Copied from original issue: gizafoundation/imperative#61_

### PR DESCRIPTION
**Pull request by ChrisBoehmCA**
Add automated test

### CODE REVIEW

File: packages/cmd/src/syntax/SyntaxValidator.ts [hunk 1]
```diff
@@ -204,7 +204,9 @@ export class SyntaxValidator {
             for (const positional of this.mCommandDefinition.positionals) {
                 if (positional.required) {
                     // Use replace to trim possible ... which is used for arrays
-                    if (!commandArguments[positional.name.replace("...","")]) {
+                    const positionalName = positional.name.replace("...", "");
+                    if (commandArguments[positionalName] == null ||
+                        (positional.type !== "stringOrEmpty" && commandArguments[positionalName] === "")) {
```
Comment (zFernand0) [inline packages/cmd/src/syntax/SyntaxValidator.ts]: :+1:
