### PR TITLE
Fix issue where required array type positionals could not be validated

### LINKED ISSUE #161: Required array-type positional arguments fail syntax validation
There is a bug where if a positional argument specified as an array by adding `...` to the end of the name such as in this example: 
```
  positionals: [
                    {
                        name: "my-array...",
                        required: true,
                        type: "string",
                        description: "gimme those strings"
                    }
                ],
```

Syntax validation will always fail with a message that my-array... was not specified

We have a PR in the works to fix this issue

### PR DESCRIPTION
**Pull request by ChrisBoehmCA**
Fix #161 where required array type positionals could not be validated
Add tests for this scenario

### CODE REVIEW

File: packages/cmd/src/syntax/SyntaxValidator.ts [hunk 1]
```diff
@@ -203,7 +203,8 @@ export class SyntaxValidator {
             const missingPositionals: ICommandPositionalDefinition[] = [];
             for (const positional of this.mCommandDefinition.positionals) {
                 if (positional.required) {
-                    if (!commandArguments[positional.name]) {
+                    // Use replace to trim possible ... which is used for arrays
+                    if (!commandArguments[positional.name.replace("...","")]) {
```
Comment (zFernand0) [inline packages/cmd/src/syntax/SyntaxValidator.ts]: :+1:

File: package.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "name": "@brightside/imperative",
-  "version": "2.1.0-alpha.201902072106",
+  "version": "2.1.1-alpha.201902072106",
```
Comment (zFernand0) [inline package.json]: :+1:

File: __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts [hunk 3]
```diff
@@ -325,6 +325,90 @@ describe("Imperative should provide advanced syntax validation rules", function
                     minValidOptions + "--always-required-string hello",
                     false, ["multiple", "--always-required-string"])();
             });
+        describe("We should be able to validate array positional arguments", function () {
```
Comment (zFernand0) [inline __tests__/src/packages/cmd/SyntaxValidator.integration.test.ts]: Thanks for adding the test
