### PR TITLE
Fix/2

### LINKED ISSUE #2: Insufficient error messages when failing to load secure credentials
**COPIED OVER**

Using a Brightside command, I received the following error:

```
Command Preparation Failed:
Unable to load the secure field "pass" associated with the profile "tso1" of type "zosmf".
Error Details:
Unable to load credentials!
```

- What is the user's next action?
- Is it possible to surface more details from KeyTar?
- Why did this occur?

### PR DESCRIPTION
**Pull request by AHumanFromCA**
## Changelog

- More detailed error message if credentials could not be loaded from the vault (Resolves #2)

### CODE REVIEW

File: packages/security/src/DefaultCredentialManager.ts [hunk 1]
```diff
@@ -41,144 +41,155 @@ import * as keytar from "keytar"; // Used for typing purposes only
...
-      } else {
-        throw this.loadError;
-      }
+    private getMissingEntryMessage(account: string) {
+        return `Could not find an entry for the service ${this.service} and account ${account} in the credential vault!\n\n` +
+            "Possible Causes:\n" +
+            "  This could have been caused by any manual removal of credentials from your vault.\n\n" +
+            "Resolutions: \n" +
+            "  Recreate the credentials in the vault for the particular service in the vault. If the error was within a profile, this " +
+            "can be achieved by recreating the profile with the --ow flag\n";
```
Comment (tucker01) [inline packages/security/src/DefaultCredentialManager.ts]: Missing period 😄

Comment (AHumanFromCA) [reply packages/security/src/DefaultCredentialManager.ts]: :astonished:
